version: "3.8"
services:
  products:
    build: ./services/product
    container_name: products-service
    ports:
      - "5000:5000"
    volumes:
      - ./services/product:/app/
      - ./protos:/app/protos
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb/grpc-shop-practice
      - SERVER_ADDRESS=products:5000
    networks:
      grpc-practice-network:
  blogs:
    build: ./services/blog
    container_name: blogs-service
    ports:
      - "5002:5002"
    volumes:
      - ./services/blog:/app/
      - ./protos:/app/protos
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb/grpc-shop-practice
      - SERVER_ADDRESS=blogs:5000
    networks:
      grpc-practice-network:
  client:
    build: ./client
    container_name: client
    volumes:
      - ./client:/app/
      - ./protos:/app/protos
    environment:
      - products_url=products:5000
      - blogs_url=blogs:5002
    depends_on:
      - products
      - blogs
    networks:
      grpc-practice-network:
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:focal
    container_name: grpc-shop-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      grpc-practice-network:
volumes:
  mongodb:
networks:
  grpc-practice-network:
    driver: bridge